apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodej-demo-app
  namespace: default
spec:
  replicas: 4                     
  selector:
    matchLabels:
      app: nodejs-demo-app
  template:
    metadata:
      labels:
        app: nodejs-demo-app
    spec:
      containers:
      - name: nodejs-demo-app
        image: legend001/nodejs-demo:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: "250m"
          requests:
            memory: 32Mi
            cpu: "200m"

        ports:
        - containerPort: 30002


apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-app-entrypoint
  namespace: default
spec:

  type: LoadBalancer
  selector:
    app: nodejs-demo-app

  ports:
    - name: http
      protocol: TCP
      port: 80             
      targetPort: 30002

    - name: https
      protocol: TCP
      port: 443            
      targetPort: 30002

